//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Przychodnia_online
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHOROBY
    {
        public decimal ID_CHOROBY { get; set; }
        public Nullable<decimal> ID_WIZYTA { get; set; }
        public string CHO_NAZWA { get; set; }
        public bool PRZEWLEKLA { get; set; }
    
        public virtual WIZYTA WIZYTA { get; set; }
    }
}
