//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Przychodnia_online
{
    using System;
    using System.Collections.Generic;
    
    public partial class KARTAPACJENTA
    {
        public KARTAPACJENTA()
        {
            this.PACJENT1 = new HashSet<PACJENT>();
            this.WIZYTA = new HashSet<WIZYTA>();
            this.LEK = new HashSet<LEK>();
        }
    
        public decimal ID_KARTAPACJENTA { get; set; }
        public Nullable<decimal> ID_PACJENT { get; set; }
        public string GRUPAKRWI { get; set; }
    
        public virtual PACJENT PACJENT { get; set; }
        public virtual ICollection<PACJENT> PACJENT1 { get; set; }
        public virtual ICollection<WIZYTA> WIZYTA { get; set; }
        public virtual ICollection<LEK> LEK { get; set; }
    }
}
