//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Przychodnia_online
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEK
    {
        public LEK()
        {
            this.KARTAPACJENTA = new HashSet<KARTAPACJENTA>();
            this.RECEPTA = new HashSet<RECEPTA>();
        }
    
        public decimal ID_LEK { get; set; }
        public string NAZWA { get; set; }
        public string ROZMIAR { get; set; }
    
        public virtual ICollection<KARTAPACJENTA> KARTAPACJENTA { get; set; }
        public virtual ICollection<RECEPTA> RECEPTA { get; set; }
    }
}
