//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Przychodnia_online
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PrzychodniaEntities : DbContext
    {
        public PrzychodniaEntities()
            : base("name=PrzychodniaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CHOROBY> CHOROBY { get; set; }
        public DbSet<KARTAPACJENTA> KARTAPACJENTA { get; set; }
        public DbSet<LEK> LEK { get; set; }
        public DbSet<LEKARZ> LEKARZ { get; set; }
        public DbSet<PACJENT> PACJENT { get; set; }
        public DbSet<RECEPTA> RECEPTA { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<WIZYTA> WIZYTA { get; set; }
    }
}
