//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Przychodnia_online
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACJENT
    {
        public PACJENT()
        {
            this.KARTAPACJENTA = new HashSet<KARTAPACJENTA>();
            this.RECEPTA = new HashSet<RECEPTA>();
            this.WIZYTA = new HashSet<WIZYTA>();
        }
    
        public decimal ID_PACJENT { get; set; }
        public Nullable<decimal> ID_KARTAPACJENTA { get; set; }
        public string PAC_IMIE { get; set; }
        public string PAC_NAZWISKO { get; set; }
        public System.DateTime PAC_DATAUR { get; set; }
        public string PAC_PESEL { get; set; }
        public decimal PAC_NRTELEFONU { get; set; }
        public string PAC_MAIL { get; set; }
        public string PAC_ADRES { get; set; }
        public string PAC_HASLO { get; set; }
    
        public virtual ICollection<KARTAPACJENTA> KARTAPACJENTA { get; set; }
        public virtual KARTAPACJENTA KARTAPACJENTA1 { get; set; }
        public virtual ICollection<RECEPTA> RECEPTA { get; set; }
        public virtual ICollection<WIZYTA> WIZYTA { get; set; }
    }
}
