//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Przychodnia_online
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEPTA
    {
        public RECEPTA()
        {
            this.LEK = new HashSet<LEK>();
        }
    
        public decimal ID_RECEPTA { get; set; }
        public Nullable<decimal> ID_LEKARZ { get; set; }
        public Nullable<decimal> ID_PACJENT { get; set; }
        public System.DateTime DATAWYSTAWIENIA { get; set; }
        public string REC_OPIS { get; set; }
    
        public virtual LEKARZ LEKARZ { get; set; }
        public virtual PACJENT PACJENT { get; set; }
        public virtual ICollection<LEK> LEK { get; set; }
    }
}
