//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Przychodnia_online
{
    using System;
    using System.Collections.Generic;
    
    public partial class WIZYTA
    {
        public WIZYTA()
        {
            this.CHOROBY = new HashSet<CHOROBY>();
        }
    
        public decimal ID_WIZYTA { get; set; }
        public Nullable<decimal> ID_PACJENT { get; set; }
        public Nullable<decimal> ID_KARTAPACJENTA { get; set; }
        public Nullable<decimal> ID_LEKARZ { get; set; }
        public System.DateTime DATA { get; set; }
        public string WIZ_OPIS { get; set; }
    
        public virtual ICollection<CHOROBY> CHOROBY { get; set; }
        public virtual KARTAPACJENTA KARTAPACJENTA { get; set; }
        public virtual LEKARZ LEKARZ { get; set; }
        public virtual PACJENT PACJENT { get; set; }
    }
}
